[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'w0rp/ale'
hook_source = 'source ~/.vim/rc/plugins/ale.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = 'source ~/.vim/rc/plugins/indentline.rc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.vim/rc/plugins/nerdtree.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_source = 'source ~/.vim/rc/plugins/vim-airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hock_source =  'source ~/.vim/rc/plugins/vim-gitgutter.rc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source = 'source ~/.vim/rc/plugins/vim-fugitive.rc.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_source = 'source ~/.vim/rc/plugins/vim-auto-save.rc.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_source = 'source ~/.vim/rc/plugins/vim-devicons.rc.vim'

[[plugins]]
repo= 'Chiel92/vim-autoformat'
hook_source = 'au BufWrite * :Autoformat'

[[plugins]]
repo = 'junegunn/fzf.vim'
build = './install --all'
hook_source = 'source ~/.vim/rc/plugins/fzf.vim.rc.vim'

[[plugins]]
repo = 'junegunn/fzf'
hook_add = 'set rtp+=~/.fzf'
depends = 'fzf'
hook_source = 'source ~/.vim/rc/plugins/fzf.rc.vim'

[[plugins]]
repo = 'mileszs/ack.vim'
hook_source = 'source ~/.vim/rc/plugins/ack.vim.rc.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = 'source ~/.vim/rc/plugins/quickrun.vim.rc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'Raimondi/delimitMate'


[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_source = 'source ~/.vim/rc/plugins/coc.nvim.rc.vim'
