[[plugins]]
repo   = 'Shougo/unite.vim'

# unite.vim を読み込んだら一緒に読み込む
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# go
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = 'source ~/.vim/rc/plugins/vim-go.rc.vim'

# json
[[plugins]]
repo  = 'elzr/vim-json'
on_ft = ['json']
hook_add = 'source ~/.vim/rc/plugins/json.rc.vim'

# html
[[plugins]]
repo  = 'mattn/emmet-vim'
# on_ft = ['html','css']
hook_add = 'source ~/.vim/rc/plugins/emmet.rc.vim'

# toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# yaml
[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = ['yaml']

# Markdown
[[plugins]]
repo  = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = 'source ~/.vim/rc/plugins/markdown.rc.vim'

[[plugins]]
repo  = 'kannokanno/previm'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo  = 'tyru/open-browser.vim'
on_ft = ['markdown', 'mkd']

#tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = 'source ~/.vim/rc/plugins/vimtex.rc.vim'

# terraform
[[plugins]]
repo  = 'hashivim/vim-terraform'
on_ft = ['tf']
hook_add = 'source ~/.vim/rc/plugins/vim-terraform.rc.vim'

# Docker
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

# scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala', 'play']

# quickrun
[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['python', 'scala', 'go', 'ruby', 'javascript']
